### ISSUE TITLE
Failed to update to glab version 1.47.0

### ISSUE THREAD

**Issue by mhagnumdw** [particledecay/asdf-glab#10]
**Describe the bug**

Failed to update to glab version 1.47.0

```
* Downloading glab release 1.47.0...
curl: (22) The requested URL returned error: 404
asdf-glab: Could not download https://gitlab.com/gitlab-org/cli/-/releases/v1.47.0/downloads/glab_1.47.0_Linux_x86_64.tar.gz
```

**Steps to reproduce**

`asdf install glab latest`

**Expected behavior**

Download version 1.47.0 successfully.

**Additional context**

There is no file `glab_1.47.0_Linux_x86_64.tar.gz` in release https://gitlab.com/gitlab-org/cli/-/releases/v1.47.0

```
asdf --version                                     
v0.14.1-f00f759
```

**Comment by chessmango** [comment]
Looks like a packaging change from https://gitlab.com/gitlab-org/cli/-/merge_requests/1701 - I'll take a look at this later if I have a gap

**Comment by rsrchboy** [comment]
Yeah.  The arch name released went from `x86_64` -> `amd64`, AFAICT :(

**Comment by pedropombeiro** [comment]
Apple silicon is also affected apparently:

<img width="990" alt="image" src="https://github.com/user-attachments/assets/a08efedc-d6fb-468d-8474-bcfdbd839bde">

**Comment by curio77** [comment]
Any chance of getting the above PR merged?

**Comment by rojosinalma** [comment]
@particledecay can we get the above PR merged please?
Every version for amd64 is broken now.

**Comment by particledecay** [comment]
Damn I usually don't miss these... sorry, flooded with github notifications :grimacing: 

Checking now!

**Comment by Cartman75** [comment]
Thanks everyone, I was able to update!
