### ISSUE TITLE
Updating link to glab?

### ISSUE THREAD

**Issue by garymh** [particledecay/asdf-glab#3]
Hi @particledecay ! GitLab adopted the `glab` project from @profclems and we're updating it over at https://gitlab.com/gitlab-org/cli now. Would you be able to change the link over to there? I'd be happy to help too :)

**Comment by particledecay** [comment]
Yes @garymh, thanks for bringing this up! I'm out of town right now but I'll try and update this as soon as I can.

**Comment by particledecay** [comment]
The link should be updated and working now for all versions 1.23.0 and up.
